spring.application.name=gateway

//auth
spring.cloud.gateway.server.webflux.routes[0].uri=lb://authentication
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webflux.routes[0].id=authentication_service

//email
spring.cloud.gateway.server.webflux.routes[1].uri=lb://email
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/email/**
spring.cloud.gateway.server.webflux.routes[1].id=email_service

//websocket
spring.cloud.gateway.server.webflux.routes[2].uri=lb://websocket
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/**
spring.cloud.gateway.server.webflux.routes[2].id=websocket_service

server.port=8080